Implement get prediction
enyason/replicate-kotlin pull request #27
Opened 2024-04-29 21:10 UTC by Lamouresparus

Closes #20

2024-04-29 21:52 UTC, mayorJAY reviewed
👍

2024-04-29 21:52 UTC, mayorjay requested changes
LGTM just one thing left, don't forget to write unit tests for the new endpoint in PredictionsApiTest

2024-04-30 01:41 UTC, enyason requested changes
LGTM

Let's write the test @mayorJAY pointed out.

2024-04-30 20:36 UTC, mayorJAY approved these changes

2024-04-30 22:13 UTC, enyason approved these changes

2024-05-01 08:07 UTC, merged